# Generated by Django 5.1.4 on 2024-12-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('created_datetime', models.DateField()),
                ('title', models.CharField(max_length=150)),
                ('content', models.CharField(max_length=500)),
            ],
        ),
    ]
